<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Loewenstark Magento License (LML 1.0).
 * It is  available through the world-wide-web at this URL:
 * http://www.loewenstark.de/licenses/lml-1.0.html
 * If you are unable to obtain it through the world-wide-web, please send an 
 * email to license@loewenstark.de so we can send you a copy immediately.
 *
 * @category   Loewenstark
 * @package    Loewenstark_OneCheckout
 * @copyright  Copyright (c) 2012 Ulrich Abelmann
 * @copyright  Copyright (c) 2012 wwg.löwenstark im Internet GmbH
 * @license    http://www.loewenstark.de/licenses/lml-1.0.html  Loewenstark Magento License (LML 1.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<div class="sub-title">
	<?php if(!$this->isCustomerLoggedIn()): ?>
		<?php echo $this->__('You already have an account? <a href="#" id="onecheckout-login">Login here.</a>') ?>
		<div id="onecheckout-login-form" style="display: none">
			<?php echo $this->getChildHtml("customer_form_login") ?>
        	<a href="<?php echo $this->helper('customer')->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
		</div>
	<?php endif; ?>
</div>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<div class="col3-set">

	<div class="col-1">
		<div>
		 	<h2 class="onecheckout-title">
				<?php echo $this->__("Billing Address") ?>
			</h2>
			<?php echo $this->getChildHtml("billing") ?> 
			<?php if(!$this->isCustomerLoggedIn()): ?>
			  <ul class="form-list">
			    <li class="control">
				<input id="login:guest" class="checkbox" type="checkbox" value="register" name="checkout_method">
				<label for="login:guest"><?php echo $this->__("Create an account") ?></label>
				</li>
			  </ul>
			<?php endif; ?>
		</div>
		<div id="shippingaddress" style="display: none">
		 	<h2 class="onecheckout-title">
				<?php echo $this->__("Shipping Address") ?>
			</h2>
			<?php echo $this->getChildHtml("shipping") ?> 
		</div>
	</div>
	
	<div class="col-2">
		<div id="shippingmethod">
		 	<h2 class="onecheckout-title">
				<?php echo $this->__("Shipping Method") ?>
			</h2>
			<?php echo $this->getChildHtml("shipping_method") ?> 
		</div>
		
		<div id="paymentmethod">
		 	<h2 class="onecheckout-title">
				<?php echo $this->__("Payment Method") ?>
			</h2>
			<?php echo $this->getChildHtml("payment") ?> 
		</div>
	</div>
		
	<div class="col-3">
		<h2 class="onecheckout-title">
			<?php echo $this->__("Summary") ?>
		</h2>
		<?php echo $this->getChildHtml('agreements') ?>
		<div id="checkout-review-load">
			<?php echo $this->getChildHtml("review") ?> 
		</div>
		<div class="clearer"></div>
		<div id="checkout-review-submit">
			<div class="buttons-set" id="review-buttons-container">
				<p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
				<?php echo $this->getChildHtml('button') ?>
				<span class="please-wait" id="review-please-wait" style="display:none;">
					<img src="<?php echo $this->getSkinUrl('onecheckout/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
				</span>
			</div>
		</div>
	</div>

</div>




<script type="text/javascript">



checkout = new OneCheckout();
checkout.ctime = "<?php echo Mage::helper("onecheckout")->s() ?>";
checkout.saveUrl = "<?php echo $this->getUrl("onecheckout/ajax/update") ?>";
checkout.failureUrl = "<?php echo $this->getUrl("checkout/cart") ?>";
checkout.completeUrl = "<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>";
checkout.successUrl = "<?php echo $this->getUrl('checkout/onepage/success') ?>";
checkout.preloginUrl = "<?php echo $this->getUrl("onecheckout/ajax/preLogin") ?>";
checkout.imsg = "<?php echo Mage::helper("onecheckout")->__("L invalid") ?>";
checkout.triggerShipping = <?php echo Mage::helper("onecheckout")->getTriggers("shipping_method") ?>;
checkout.triggerPayment = <?php echo Mage::helper("onecheckout")->getTriggers("payment_method") ?>;
checkout.triggerReview = <?php echo Mage::helper("onecheckout")->getTriggers("review") ?>;
review = new Review($('checkout-agreements'));

Event.observe(window, 'load', function() {
	payment.initWhatIsCvvListeners();
	payment.init();
	checkout.init();
});

</script>