<?php
/**
 *
 * @category   MageProfis
 * @package    MageProfis_OneCheckout
 * @copyright  Copyright (c) 2015 Ulrich Abelmann
 * @copyright  Copyright (c) 2015 MageProfis GmbH
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_attributes = Mage::helper("onecheckout/attributes")->getAttributes($this->getParentBlock()->getItem())): ?>
	<dl class="item-options">
	<?php foreach($_attributes as $_attribute): ?>
        <dt><?php echo $_attribute['label'] ?></dt>
        <dd><?php echo $_attribute['value'] ?></dd>
    <?php endforeach; ?>
	</dl>
<?php endif; ?>